"""Hybrid state-balanced active-space selector for helium at fixed 20Q.

The selector is fully theory-driven. It uses no experimental excited-state
energy or oscillator strength to choose orbitals. The 10 spatial modes are
assembled from three information classes:

1. dominant ground-state natural orbital (correlation anchor),
2. two scalar radial Krylov directions generated by r^2 from that anchor,
3. three lowest bright TDA/NTO virtual directions (the Cartesian 1P manifold),
4. lowest-energy canonical directions to fill the remaining budget.

The goal is to retain both low-lying 2s-like radial flavor and 2p-like bright
flavor inside the same 10-spatial / 20-spin-orbital register.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

from .active_space import _append_orthonormal


@dataclass(frozen=True)
class HybridActiveSpaceReceipt:
    protocol: str
    source_basis: str
    source_spatial_orbitals: int
    target_spatial_orbitals: int
    target_spin_orbitals: int
    compression_backend: str
    ground_fci_hartree: float
    dominant_natural_occupation: float
    radial_krylov_orders: Tuple[int, ...]
    selected_tda_states: Tuple[int, ...]
    selected_tda_excitation_eV: Tuple[float, ...]
    selected_tda_oscillator_strengths: Tuple[float, ...]
    selected_labels: Tuple[str, ...]

    def as_dict(self) -> Dict[str, object]:
        return asdict(self)


def build_helium_hybrid_20q(
    source_basis: Any,
    source_label: str,
    target_spatial: int = 10,
    n_tda_states: int = 16,
    bright_threshold: float = 1e-5,
):
    if target_spatial != 10:
        raise ValueError("Q1 hybrid contract is fixed at 10 spatial / 20 spin orbitals")
    try:
        from pyscf import ao2mo, fci, gto, scf, tdscf
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("hybrid Q1 selector requires the OES q1 extra (PySCF)") from exc

    mol = gto.M(
        atom="He 0 0 0",
        basis=source_basis,
        unit="Bohr",
        charge=0,
        spin=0,
        verbose=0,
    )
    mf = scf.RHF(mol)
    mf.conv_tol = 1e-12
    mf.kernel()
    if not mf.converged:
        raise RuntimeError("helium RHF did not converge")

    C = np.asarray(mf.mo_coeff, dtype=float)
    overlap = np.asarray(mf.get_ovlp(), dtype=float)
    n_full = C.shape[1]
    h1 = C.T @ mf.get_hcore() @ C
    eri = ao2mo.kernel(mol, C, compact=False).reshape((n_full,) * 4)

    # Ground-state correlation anchor from an exact two-electron source FCI.
    solver = fci.direct_spin0.FCI()
    solver.conv_tol = 1e-11
    e_fci, ci0 = solver.kernel(h1, eri, n_full, 2, ecore=float(mol.energy_nuc()))
    dm1 = np.asarray(solver.make_rdm1(ci0, n_full, 2), dtype=float)
    dm1 = 0.5 * (dm1 + dm1.T)
    occ, no_vec = np.linalg.eigh(dm1)
    order = np.argsort(occ)[::-1]
    occ = occ[order]
    no_vec = no_vec[:, order]
    dominant = no_vec[:, 0]

    vectors: List[np.ndarray] = []
    labels: List[str] = []
    _append_orthonormal(vectors, labels, dominant, "ground-NO[0]")

    # Scalar radial Krylov block. Subtracting the component parallel to the
    # ground anchor is handled automatically by _append_orthonormal.
    r2_ao = mol.intor("int1e_r2", hermi=1)
    r2_mo = C.T @ r2_ao @ C
    radial = dominant.copy()
    radial_orders: List[int] = []
    for order_k in (1, 2):
        radial = r2_mo @ radial
        if _append_orthonormal(vectors, labels, radial, f"r2-Krylov[{order_k}]|ground-NO[0]"):
            radial_orders.append(order_k)

    # Vector bright block from ab-initio response. For isolated helium the
    # lowest 1P response is triply degenerate, so retain all three directions.
    td = tdscf.TDA(mf)
    td.singlet = True
    td.nstates = n_tda_states
    tda_e, _ = td.kernel()
    tda_e = np.asarray(tda_e, dtype=float)
    osc = np.asarray(td.oscillator_strength(), dtype=float)
    bright = [i for i, f in enumerate(osc) if float(f) > bright_threshold][:3]
    if len(bright) < 3:
        raise RuntimeError(f"hybrid selector expected three bright TDA roots, got {len(bright)}")

    nocc = int(np.count_nonzero(np.asarray(mf.mo_occ) > 0))
    selected_states: List[int] = []
    selected_exc: List[float] = []
    selected_osc: List[float] = []
    HARTREE_TO_EV = 27.211_386_245_981
    for idx in bright:
        _weights, nto_ao = td.get_nto(state=int(idx) + 1, threshold=0.0)
        nto_ao = np.asarray(nto_ao, dtype=float)
        if nto_ao.shape[1] <= nocc:
            raise RuntimeError("hybrid selector NTO matrix lacks a virtual NTO")
        nto_virtual_mo = C.T @ overlap @ nto_ao[:, nocc]
        if _append_orthonormal(
            vectors,
            labels,
            nto_virtual_mo,
            f"TDA-NTO-virtual[state={int(idx)+1}]",
        ):
            selected_states.append(int(idx) + 1)
            selected_exc.append(float(tda_e[idx] * HARTREE_TO_EV))
            selected_osc.append(float(osc[idx]))

    # Fill residual capacity only after both radial and bright sectors have
    # received explicit representation.
    for idx in np.argsort(np.asarray(mf.mo_energy, dtype=float)):
        if len(vectors) >= target_spatial:
            break
        unit = np.zeros(n_full, dtype=float)
        unit[int(idx)] = 1.0
        _append_orthonormal(vectors, labels, unit, f"canonical-MO[{int(idx)}]")

    for k in range(n_full):
        if len(vectors) >= target_spatial:
            break
        _append_orthonormal(vectors, labels, no_vec[:, k], f"ground-NO[{k}]")

    if len(vectors) != target_spatial:
        raise RuntimeError(f"hybrid selector constructed only {len(vectors)} independent orbitals")

    U = np.column_stack(vectors)
    if not np.allclose(U.T @ U, np.eye(target_spatial), atol=1e-10):
        raise RuntimeError("hybrid selector lost MO-space orthonormality")

    receipt = HybridActiveSpaceReceipt(
        protocol="D-AUG-HYBRID-R2-KRYLOV-TDA-NTO-20Q",
        source_basis=str(source_label),
        source_spatial_orbitals=n_full,
        target_spatial_orbitals=target_spatial,
        target_spin_orbitals=2 * target_spatial,
        compression_backend="REFERENCE_GROUND_FCI_RDM1_PLUS_R2_KRYLOV_PLUS_TDA_NTO",
        ground_fci_hartree=float(e_fci),
        dominant_natural_occupation=float(occ[0]),
        radial_krylov_orders=tuple(radial_orders),
        selected_tda_states=tuple(selected_states),
        selected_tda_excitation_eV=tuple(selected_exc),
        selected_tda_oscillator_strengths=tuple(selected_osc),
        selected_labels=tuple(labels),
    )
    return mol, mf, C @ U, receipt
