"""Symmetry-complete block selector for helium at exactly 20 spin orbitals.

The fixed 10-spatial-orbital register is decomposed into complete SO(3)-like
one-particle blocks:

    4 scalar radial s-like modes + 3 lowest p-like response modes
    + 3 scalar-radially excited p-like modes = 10 spatial = 20 spin.

The second p copy is generated by applying the scalar r^2 operator to every
member of the first TDA/NTO p manifold.  Therefore an entire 3-dimensional
vector block is retained rather than an arbitrary subset.  No measured
spectrum enters active-space selection.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any, Dict, List, Tuple

import numpy as np

from .active_space import _append_orthonormal


@dataclass(frozen=True)
class BlockActiveSpaceReceipt:
    protocol: str
    source_basis: str
    source_spatial_orbitals: int
    target_spatial_orbitals: int
    target_spin_orbitals: int
    compression_backend: str
    ground_fci_hartree: float
    dominant_natural_occupation: float
    scalar_mode_count: int
    scalar_krylov_orders: Tuple[int, ...]
    p_block_count: int
    p_modes_per_block: int
    selected_tda_states: Tuple[int, ...]
    selected_tda_excitation_eV: Tuple[float, ...]
    selected_tda_oscillator_strengths: Tuple[float, ...]
    selected_labels: Tuple[str, ...]

    def as_dict(self) -> Dict[str, object]:
        return asdict(self)


def build_helium_s4_p6_20q(
    source_basis: Any,
    source_label: str,
    n_tda_states: int = 16,
    bright_threshold: float = 1e-5,
):
    try:
        from pyscf import ao2mo, fci, gto, scf, tdscf
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("s4+p6 Q1 selector requires the OES q1 extra (PySCF)") from exc

    mol = gto.M(atom="He 0 0 0", basis=source_basis, unit="Bohr", charge=0, spin=0, verbose=0)
    mf = scf.RHF(mol)
    mf.conv_tol = 1e-12
    mf.kernel()
    if not mf.converged:
        raise RuntimeError("helium RHF did not converge")

    C = np.asarray(mf.mo_coeff, dtype=float)
    overlap = np.asarray(mf.get_ovlp(), dtype=float)
    n_full = C.shape[1]
    h1 = C.T @ mf.get_hcore() @ C
    eri = ao2mo.kernel(mol, C, compact=False).reshape((n_full,) * 4)

    solver = fci.direct_spin0.FCI()
    solver.conv_tol = 1e-11
    e_fci, ci0 = solver.kernel(h1, eri, n_full, 2, ecore=float(mol.energy_nuc()))
    dm1 = np.asarray(solver.make_rdm1(ci0, n_full, 2), dtype=float)
    dm1 = 0.5 * (dm1 + dm1.T)
    occ, no_vec = np.linalg.eigh(dm1)
    order = np.argsort(occ)[::-1]
    occ = occ[order]
    no_vec = no_vec[:, order]
    dominant = no_vec[:, 0]

    r2_ao = mol.intor("int1e_r2", hermi=1)
    r2_mo = C.T @ r2_ao @ C

    vectors: List[np.ndarray] = []
    labels: List[str] = []
    if not _append_orthonormal(vectors, labels, dominant, "s0:ground-NO[0]"):
        raise RuntimeError("could not seed scalar ground mode")

    # Ground plus three radial Krylov directions = four scalar modes.
    radial = dominant / np.linalg.norm(dominant)
    scalar_orders: List[int] = []
    for k in range(1, 4):
        radial = r2_mo @ radial
        norm = float(np.linalg.norm(radial))
        if norm <= 1e-14:
            raise RuntimeError(f"scalar Krylov vector vanished at order {k}")
        radial = radial / norm
        if not _append_orthonormal(vectors, labels, radial, f"s{k}:r2-Krylov[{k}]"):
            raise RuntimeError(f"scalar Krylov space lost rank before required order {k}")
        scalar_orders.append(k)
    if len(vectors) != 4:
        raise RuntimeError(f"expected four scalar modes, got {len(vectors)}")

    # First complete p block from the lowest bright TDA/NTO triplet.
    td = tdscf.TDA(mf)
    td.singlet = True
    td.nstates = n_tda_states
    tda_e, _ = td.kernel()
    tda_e = np.asarray(tda_e, dtype=float)
    osc = np.asarray(td.oscillator_strength(), dtype=float)
    bright = [i for i, f in enumerate(osc) if float(f) > bright_threshold][:3]
    if len(bright) != 3:
        raise RuntimeError(f"expected complete three-state bright manifold, got {len(bright)}")

    nocc = int(np.count_nonzero(np.asarray(mf.mo_occ) > 0))
    p1_raw: List[np.ndarray] = []
    selected_states: List[int] = []
    selected_exc: List[float] = []
    selected_osc: List[float] = []
    HARTREE_TO_EV = 27.211_386_245_981
    for idx in bright:
        _weights, nto_ao = td.get_nto(state=int(idx) + 1, threshold=0.0)
        nto_ao = np.asarray(nto_ao, dtype=float)
        if nto_ao.shape[1] <= nocc:
            raise RuntimeError("NTO matrix lacks a virtual p direction")
        pvec = C.T @ overlap @ nto_ao[:, nocc]
        p1_raw.append(pvec.copy())
        if not _append_orthonormal(vectors, labels, pvec, f"p1:TDA-NTO[state={int(idx)+1}]"):
            raise RuntimeError("first complete p block lost rank")
        selected_states.append(int(idx) + 1)
        selected_exc.append(float(tda_e[idx] * HARTREE_TO_EV))
        selected_osc.append(float(osc[idx]))

    if len(vectors) != 7:
        raise RuntimeError(f"expected 4s+3p after first p block, got {len(vectors)} modes")

    # Second complete p radial copy. Apply the same scalar r^2 operator to all
    # three p directions; projection may rotate the block but may not drop a
    # member. This is the key symmetry-preservation gate.
    for axis, pvec in enumerate(p1_raw):
        p2 = r2_mo @ pvec
        norm = float(np.linalg.norm(p2))
        if norm <= 1e-14:
            raise RuntimeError(f"second p-block vector vanished for component {axis}")
        p2 = p2 / norm
        if not _append_orthonormal(vectors, labels, p2, f"p2:r2|p1[{axis}]"):
            raise RuntimeError(f"second complete p block lost rank at component {axis}")

    if len(vectors) != 10:
        raise RuntimeError(f"s4+p6 selector produced {len(vectors)} modes instead of 10")
    U = np.column_stack(vectors)
    if not np.allclose(U.T @ U, np.eye(10), atol=1e-10):
        raise RuntimeError("s4+p6 selector lost MO-space orthonormality")

    receipt = BlockActiveSpaceReceipt(
        protocol="D-AUG-SYMMETRY-BLOCK-S4-P3-P3R2-20Q",
        source_basis=str(source_label),
        source_spatial_orbitals=n_full,
        target_spatial_orbitals=10,
        target_spin_orbitals=20,
        compression_backend="REFERENCE_GROUND_FCI_RDM1_PLUS_SCALAR_R2_KRYLOV_PLUS_TWO_COMPLETE_P_BLOCKS",
        ground_fci_hartree=float(e_fci),
        dominant_natural_occupation=float(occ[0]),
        scalar_mode_count=4,
        scalar_krylov_orders=tuple(scalar_orders),
        p_block_count=2,
        p_modes_per_block=3,
        selected_tda_states=tuple(selected_states),
        selected_tda_excitation_eV=tuple(selected_exc),
        selected_tda_oscillator_strengths=tuple(selected_osc),
        selected_labels=tuple(labels),
    )
    return mol, mf, C @ U, receipt
