"""Symmetry-preserving helium active space at exactly 20 spin orbitals.

For an isolated atom the active space must preserve complete angular multiplets.
This selector freezes a 10-spatial-orbital layout

    7 scalar radial modes + 3 Cartesian p-like modes = 10 spatial = 20 spin.

The scalar block is a ground-natural-orbital radial Krylov space generated by
r^2. The vector block is the complete triply-degenerate lowest bright TDA/NTO
manifold. No measured spectrum is used to select the subspace.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any, Dict, List, Tuple

import numpy as np

from .active_space import _append_orthonormal


@dataclass(frozen=True)
class SPActiveSpaceReceipt:
    protocol: str
    source_basis: str
    source_spatial_orbitals: int
    target_spatial_orbitals: int
    target_spin_orbitals: int
    compression_backend: str
    ground_fci_hartree: float
    dominant_natural_occupation: float
    radial_mode_count: int
    radial_krylov_orders: Tuple[int, ...]
    p_mode_count: int
    selected_tda_states: Tuple[int, ...]
    selected_tda_excitation_eV: Tuple[float, ...]
    selected_tda_oscillator_strengths: Tuple[float, ...]
    selected_labels: Tuple[str, ...]

    def as_dict(self) -> Dict[str, object]:
        return asdict(self)


def build_helium_sp_balanced_20q(
    source_basis: Any,
    source_label: str,
    n_tda_states: int = 16,
    bright_threshold: float = 1e-5,
):
    try:
        from pyscf import ao2mo, fci, gto, scf, tdscf
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("s7+p3 Q1 selector requires the OES q1 extra (PySCF)") from exc

    mol = gto.M(atom="He 0 0 0", basis=source_basis, unit="Bohr", charge=0, spin=0, verbose=0)
    mf = scf.RHF(mol)
    mf.conv_tol = 1e-12
    mf.kernel()
    if not mf.converged:
        raise RuntimeError("helium RHF did not converge")

    C = np.asarray(mf.mo_coeff, dtype=float)
    overlap = np.asarray(mf.get_ovlp(), dtype=float)
    n_full = C.shape[1]
    h1 = C.T @ mf.get_hcore() @ C
    eri = ao2mo.kernel(mol, C, compact=False).reshape((n_full,) * 4)

    solver = fci.direct_spin0.FCI()
    solver.conv_tol = 1e-11
    e_fci, ci0 = solver.kernel(h1, eri, n_full, 2, ecore=float(mol.energy_nuc()))
    dm1 = np.asarray(solver.make_rdm1(ci0, n_full, 2), dtype=float)
    dm1 = 0.5 * (dm1 + dm1.T)
    occ, no_vec = np.linalg.eigh(dm1)
    order = np.argsort(occ)[::-1]
    occ = occ[order]
    no_vec = no_vec[:, order]
    dominant = no_vec[:, 0]

    vectors: List[np.ndarray] = []
    labels: List[str] = []
    if not _append_orthonormal(vectors, labels, dominant, "s:ground-NO[0]"):
        raise RuntimeError("could not seed scalar ground mode")

    # Build six additional scalar modes. Normalizing each raw Krylov iterate
    # prevents high powers of r^2 from creating avoidable conditioning issues.
    r2_ao = mol.intor("int1e_r2", hermi=1)
    r2_mo = C.T @ r2_ao @ C
    radial = dominant / np.linalg.norm(dominant)
    radial_orders: List[int] = []
    for k in range(1, 7):
        radial = r2_mo @ radial
        raw_norm = float(np.linalg.norm(radial))
        if raw_norm <= 1e-14:
            raise RuntimeError(f"radial Krylov vector vanished at order {k}")
        radial = radial / raw_norm
        if not _append_orthonormal(vectors, labels, radial, f"s:r2-Krylov[{k}]"):
            raise RuntimeError(f"radial Krylov space lost rank at order {k}")
        radial_orders.append(k)

    if len(vectors) != 7:
        raise RuntimeError(f"expected seven scalar modes, got {len(vectors)}")

    # Add exactly the complete lowest p-like bright manifold. Keeping all three
    # NTO directions together is the symmetry gate; no arbitrary partial p block
    # is permitted.
    td = tdscf.TDA(mf)
    td.singlet = True
    td.nstates = n_tda_states
    tda_e, _ = td.kernel()
    tda_e = np.asarray(tda_e, dtype=float)
    osc = np.asarray(td.oscillator_strength(), dtype=float)
    bright = [i for i, f in enumerate(osc) if float(f) > bright_threshold][:3]
    if len(bright) != 3:
        raise RuntimeError(f"expected complete three-state bright manifold, got {len(bright)}")

    nocc = int(np.count_nonzero(np.asarray(mf.mo_occ) > 0))
    selected_states: List[int] = []
    selected_exc: List[float] = []
    selected_osc: List[float] = []
    HARTREE_TO_EV = 27.211_386_245_981
    for idx in bright:
        _weights, nto_ao = td.get_nto(state=int(idx) + 1, threshold=0.0)
        nto_ao = np.asarray(nto_ao, dtype=float)
        if nto_ao.shape[1] <= nocc:
            raise RuntimeError("NTO matrix lacks virtual p direction")
        nto_virtual_mo = C.T @ overlap @ nto_ao[:, nocc]
        if not _append_orthonormal(vectors, labels, nto_virtual_mo, f"p:TDA-NTO[state={int(idx)+1}]"):
            raise RuntimeError("complete p manifold lost rank during projection")
        selected_states.append(int(idx) + 1)
        selected_exc.append(float(tda_e[idx] * HARTREE_TO_EV))
        selected_osc.append(float(osc[idx]))

    if len(vectors) != 10:
        raise RuntimeError(f"s7+p3 selector produced {len(vectors)} modes instead of 10")
    U = np.column_stack(vectors)
    if not np.allclose(U.T @ U, np.eye(10), atol=1e-10):
        raise RuntimeError("s7+p3 selector lost MO-space orthonormality")

    receipt = SPActiveSpaceReceipt(
        protocol="D-AUG-SP-SYMMETRY-S7-P3-20Q",
        source_basis=str(source_label),
        source_spatial_orbitals=n_full,
        target_spatial_orbitals=10,
        target_spin_orbitals=20,
        compression_backend="REFERENCE_GROUND_FCI_RDM1_PLUS_SCALAR_R2_KRYLOV_PLUS_COMPLETE_TDA_NTO_P_MANIFOLD",
        ground_fci_hartree=float(e_fci),
        dominant_natural_occupation=float(occ[0]),
        radial_mode_count=7,
        radial_krylov_orders=tuple(radial_orders),
        p_mode_count=3,
        selected_tda_states=tuple(selected_states),
        selected_tda_excitation_eV=tuple(selected_exc),
        selected_tda_oscillator_strengths=tuple(selected_osc),
        selected_labels=tuple(labels),
    )
    return mol, mf, C @ U, receipt
